doc: update readme
coding-circle/charades pull request #97
Opened 2021-01-10 17:54 UTC by jacten

Updated documentation a bit. Nothing crazy as I am lazy but just more up to date.

2021-01-10 18:59 UTC, jgsheppa commented on README.md
> +I put an example `.env` file in `.env.sample` feel free to `mv .env.sample .env` to get started.
I like the new explanation of the MongoDB set up. Nice job!

2021-01-10 19:01 UTC, jgsheppa commented on documentation/Timer.md
> +Unfortunatly `setInterval` is unreliable. If a users computer or phone is under heavy load, the interval will fire late. Similarly, if the users phone goes to sleep or navigates away from the browser
Unfortunately is missing an 'e.'

2021-01-10 21:42 UTC, jgsheppa commented on documentation/Timer.md
> +Two fix the issues caused by setInterval, we use recursivly call setTimeout every 10th of a second until the time runs out. Every 10th a second we re-calculate the time remaining and update the count
'To' instead of 'Two.'

2021-01-10 21:43 UTC, jgsheppa commented on documentation/Timer.md
> +Two fix the issues caused by setInterval, we use recursivly call setTimeout every 10th of a second until the time runs out. Every 10th a second we re-calculate the time remaining and update the count
Every 10th **of** a second...

2021-01-10 21:45 UTC, jgsheppa requested changes
I added a few comments where I saw small typos. Little stuff, but thought I should let you know.

2021-01-11 20:19 UTC, chedgo commented on documentation/Timer.md
> +Two fix the issues caused by setInterval, we use recursivly call setTimeout every 10th of a second until the time runs out. Every 10th a second we re-calculate the time remaining and update the count
recursivly

2021-01-11 20:48 UTC, jacten commented on documentation/Timer.md
> +Unfortunatly `setInterval` is unreliable. If a users computer or phone is under heavy load, the interval will fire late. Similarly, if the users phone goes to sleep or navigates away from the browser
how unfortunate

2021-01-11 20:52 UTC, jacten commented
Thanks for fixes @chedgo  and @jgsheppa . I'll just merge since i'm admin and didn't do anything besides fix grammar / spelling.

2021-01-11 20:52 UTC, merged